// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhX909xs6h4Fn_c0PvaNVE4hrwiijQPTI',
    appId: '1:509554553544:web:6808308cca00b2c2faebfd',
    messagingSenderId: '509554553544',
    projectId: 'kriminal-30866',
    authDomain: 'kriminal-30866.firebaseapp.com',
    storageBucket: 'kriminal-30866.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWEetQZFqvTTou4P0Ghys9YQm9M9C0EVE',
    appId: '1:509554553544:android:cb96081ffb5ebb4cfaebfd',
    messagingSenderId: '509554553544',
    projectId: 'kriminal-30866',
    storageBucket: 'kriminal-30866.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhmTimk5QIHkxoxxQ0T4aayOGik0Qm1SM',
    appId: '1:509554553544:ios:bbb611808f1f6082faebfd',
    messagingSenderId: '509554553544',
    projectId: 'kriminal-30866',
    storageBucket: 'kriminal-30866.appspot.com',
    iosBundleId: 'com.mrcodefrost.kriminalFashionEcommerce',
  );
}
